
image:
  file: .gitpod.Dockerfile
tasks:
  - init: "scripts/bootstrap-limine && cargo build"
    command: cargo watch -x run



vscode:
  extensions:
    - matklad.rust-analyzer
    - serayuzgur.crates
